name: quickstart
description: |
  A prototype for your app with routing, tabs, bottom navigation, header, footer, logo, menu,
  language switch, Firebase authentication, and more. Set up in seconds.

repository: https://github.com/alexeyinkin/flutter-quickstart
version: 0.1.0-3.dev

topics:
  - template
  - framework
  - layout
  - boilerplate

environment:
  sdk: ^3.5.0-180

dependencies:
  app_state: ^0.9.4
  cloud_firestore: ^5.0.1
  collection: ^1.17.2
  easy_localization: ^3.0.7
  easy_localization_multi: ^0.2.0
  easy_localization_yaml: ^0.1.2
  enum_map: ^0.4.0-2.dev
  firebase_analytics: ^11.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flag: ^7.0.0
  flutter: { sdk: flutter }
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  keyed_collection_widgets: ^0.4.3
  model_fetch: ^0.5.6
  model_fetch_firestore: ^0.6.0-2.dev
  model_interfaces: ^0.3.1
  shared_preferences: ^2.2.3
  url_strategy: ^0.2.0
  version: ^3.0.2

dev_dependencies:
  total_lints: ^3.4.0

dependency_overrides:
  #model_fetch_firestore: { path: ../../dart/dart-model-fetch/model_fetch_firestore }

flutter:
  assets:
    - assets/translations/en_GB.yaml
    - assets/translations/ru_RU.yaml
