name: quickstart
description: |
  A prototype for your app with routing, tabs, bottom navigation, header, footer, logo, menu,
  language switch, Firebase authentication, and more. Set up in seconds.

repository: https://github.com/alexeyinkin/flutter-quickstart
version: 0.1.0-11.dev

topics:
  - template
  - framework
  - layout
  - boilerplate

environment:
  sdk: ^3.5.0

dependencies:
  app_state: ^0.9.4
  chewie: ^1.8.4
  clock: ^1.1.1
  cloud_firestore: ^5.0.1
  cloud_functions: ^5.1.3
  collection: ^1.17.2
  common_macros: ^0.1.0-7.dev
  crypto: ^3.0.5
  diacritic: ^0.1.6
  easy_localization: ^3.0.7
  easy_localization_multi: ^0.2.0
  easy_localization_yaml: ^0.1.2
  enum_map: ^0.4.0-2.dev
#  firebase_analytics: ^11.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.3.1
  flag: ^7.0.0
  flutter: { sdk: flutter }
  fluttertoast: ^8.2.6
  get_thumbnail_video: ^0.6.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  keyed_collection_widgets: ^0.4.3
  mime: ^1.0.6
  model_editors: ^0.4.3
  model_fetch: ^0.6.3
  model_fetch_firestore: ^0.6.3
  model_fetch_flutter: ^0.6.3
  model_interfaces: ^0.3.4
  progress_future: ^0.1.0
  shared_preferences: ^2.2.3
  url_strategy: ^0.2.0
  version: ^3.0.2
  video_player: ^2.9.1

dev_dependencies:
  total_lints: ^3.4.0

dependency_overrides:
  #model_editors: { path: ../flutter-model-editors }
  #model_fetch: { path: ../dart-model-fetch/model_fetch }
  #model_fetch_firestore: { path: ../dart-model-fetch/model_fetch_firestore }
  #model_fetch_flutter: { path: ../dart-model-fetch/model_fetch_flutter }
  #model_interfaces: { path: ../../dart/dart-model-interfaces }
  #progress_future: { path: ../dart-progress-future }

flutter:
  assets:
    - assets/translations/en_US.yaml
    - assets/translations/ru_RU.yaml
